# Basic Information 
title: Yangyuxuan Kang
position: AI Research Scientist
affiliation: Intel
affiliation_link: https://www.intel.com/
affiliation_logo: 
email: yangyuxuan.kang (at) intel.com

# Search Engine Optimization (SEO)
keywords: yangyuxuan kang, kang yangyuxuan, kangyang yuxuan, yuxuan kangyang
description: Yaoyao Liu is an assistant professor at the University of Illinois Urbana-Champaign. His research lies in digital human, efficient llm inference, knowledge graph.

# The option is used to enable the Illinois template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=GFqsXbAAAAAJ
github_link: https://github.com/kyang-06

# Images 
avatar: ./assets/img/profile.jpg

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
